kDataPath: c:/workspace/turtle-data/operation/kdatas
reportPath: C:/workspace/turtle-data/operation/reports
dailyTop100File: C:/workspace/turtle-data/operation/dailyTop100.txt
avaTop50File: C:/workspace/turtle-data/operation/avaTop50.txt
articleFile: C:/workspace/turtle-data/operation/article.txt
bluechipsFile: C:/workspace/turtle-data/simulation/bluechipids.txt




