kDataPath: c:/workspace/turtle-data/simulation/kdatas
reportPath: C:/workspace/turtle-data/simulation/reports
dailyTop100File: C:/workspace/turtle-data/simulation/dailyTop100.txt
avaTop50File: C:/workspace/turtle-data/simulation/avaTop50.txt
articlesFile: C:/workspace/turtle-data/simulation/articles.txt
bluechipsFile: C:/workspace/turtle-data/simulation/bluechipids.txt
cagrsPath: C:/workspace/turtle-data/simulation/cagrs
cagrTop50File: C:/workspace/turtle-data/simulation/cagrTop50.txt
onhandsFile: C:/workspace/turtle-data/simulation/onhands.json
cagrTopFile: C:/workspace/turtle-data/simulation/cagrTop.txt





