spring: 
  profiles: 
    active: dev
server:
  port: 8088
 
 #配置日志
logging:
  #配置日志文件路径
  level:
    com.rhb: error #不同目录下的日志可配置不同级别
    org.springfromework: error
  #采用相对路径方式将日志文件输出到【log\turtle.log】
  file: log\turtle1.log
  
  
 #tushare配置
tonken: 175936caa4637bc9ac8e5e75ac92eff6887739ca6be771b81653f278
