kDataPath: D:/prod/turtle/data/kdatas
reportPath: D:/prod/turtle/data/reports
dailyTop100File: D:/prod/turtle/data/dailyTop100.txt
avaTop50File: D:/prod/turtle/data/avaTop50.txt
articlesFile: D:/prod/turtle/data/articles.txt
bluechipsFile: D:/prod/turtle/data/bluechipids.txt
cagrsPath: D:/prod/turtle/data/cagrs
cagrTop50File: D:/prod/turtle/data/cagrTop50.txt
holdsFile: D:/prod/turtle/data/holds.txt
cagrTopFile: D:/prod/turtle/data/cagrTop.txt
preysFile: D:/prod/turtle/data/preys.csv





