kDataPath: D:/dev/turtle-data/kdatas
reportPath: D:/dev/turtle-data/reports
dailyTop100File: D:/dev/turtle-data/dailyTop100.txt
avaTop50File: D:/dev/turtle-data/avaTop50.txt
articlesFile: D:/dev/turtle-data/articles.txt
bluechipsFile: D:/dev/turtle-data/bluechipids.txt
cagrsPath: D:/dev/turtle-data/cagrs
cagrTop50File: D:/dev/turtle-data/cagrTop50.txt
holdsFile: D:/dev/turtle-data/holds.txt
cagrTopFile: D:/dev/turtle-data/cagrTop.txt
preysFile: D:/dev/turtle-data/preys.csv





