kDataPath: c:/workspace/turtle-data/kdatas
reportPath: C:/workspace/turtle-data/reports
dataPath: C:/workspace/turtle-data
dailyTop100: C:/workspace/turtle-data/dailyTop100.txt
avaTop50: C:/workspace/turtle-data/avaTop50.txt



